export interface TopicCategory {
  id: number
  name: string
  topics: string[]
}

export const topics: TopicCategory[] = [
  {
    id: 1,
    name: "Number",
    topics: [
      "Addition and Subtraction",
      "Multiplication and Division",
      "Time",
      "Metric Conversions",
      "Place Value",
      "Rounding",
      "Negative Numbers",
      "Powers and Roots",
      "The Order of Operations",
      "Factors, Multiples and Primes",
      "Fractions",
      "Fractions of an Amount",
      "Fractions, Decimals and Percentages",
      "Estimation",
      "Percentages",
      "Percentage Change",
      "Reverse Percentages",
      "Repeated Percentage Change",
      "Error Intervals",
      "Exchange Rates",
      "Conversions and Units",
      "Best Buys",
      "Standard Form",
      "Compound Interest and Depreciation",
      "Surds",
      "Bounds",
      "Converting Recurring Decimals to Fractions",
      "Compound Measures",
    ],
  },
  {
    id: 2,
    name: "Algebra",
    topics: [
      "Writing, Simplifying and Ordering Fractions",
      "Collecting Like Terms",
      "Writing an Expression",
      "Substitution",
      "Function Machines",
      "Solving One Step Equations",
      "Solving Equations",
      "Solving Quadratics",
      "Solving Simultaneous Equations Graphically",
      "Solving Simultaneous Equations",
      "Simultaneous Equations",
      "Expand and Factorise",
      "Expanding and Factorising Quadratics",
      "Expanding Triple Brackets",
      "Factorising Harder Quadratics",
      "Algebraic Fractions",
      "Changing the Subject of a Formula",
      "Rearranging Harder Formulae",
      "Quadratic Graphs",
      "Cubic/Reciprocal Graphs",
      "Gradient of a Line",
      "Equation of a Line",
      "Parallel and Perpendicular Lines",
      "Inequalities",
      "Inequalities on Graphs",
      "Sequences (nth term)",
      "Quadratic Sequences",
      "Completing the Square",
      "Quadratic Inequalities",
      "Forming and Solving Equations",
      "Proof",
      "The Product Rule for Counting",
      "Solving Equations using Iteration",
      "Inverse and Composite Functions",
      "Transforming Graphs y=f(x)",
      "Quadratic Formula",
    ],
  },
  {
    id: 3,
    name: "Ratio, Proportion and Rates of Change",
    topics: [
      "Writing and Simplifying Ratio",
      "Sharing Ratio",
      "Ratio Fraction Problems",
      "Ratio Problems 2",
      "Recipe Proportions",
      "Direct and Inverse Proportion",
      "Scale Drawings",
      "Speed/Distance/Time (under Compound Measures)",
      "Real Life Graphs",
      "Similar Shapes (Lengths)",
      "Similar Shapes (Area and Volume)",
      "Enlarging with Negative Scale Factors",
      "Best Buys",
    ],
  },
  {
    id: 4,
    name: "Geometry and Measures",
    topics: [
      "Angles",
      "Angles in Parallel Lines",
      "Angles in Polygons",
      "Area and Perimeter",
      "Area of Compound Shapes",
      "Surface Area",
      "Volume of Prisms",
      "Volume and Surface Area of Cylinders",
      "Spheres and Cones",
      "Sectors and Arcs",
      "Finding the Area of Any Triangle",
      "The Sine Rule",
      "The Cosine Rule",
      "Pythagoras",
      "3D Pythagoras and Trigonometry",
      "SOHCAHTOA",
      "Exact trig values",
      "Congruent Triangles",
      "Coordinates",
      "Drawing Graphs",
      "Rotations",
      "Reflections",
      "Enlargements",
      "Translations",
      "Mixed Transformations",
      "Rotations Solutions",
      "Reflections Solutions",
      "Enlargements Solutions",
      "Translations Solutions",
      "Mixed Transformations Solutions",
      "Loci and Construction",
      "Bearings",
      "Plans and Elevations",
      "Circle Theorems",
      "Proof of the Circle Theorems",
      "Perpendicular Lines",
      "Vectors",
    ],
  },
  {
    id: 5,
    name: "Statistics",
    topics: [
      "Pictograms",
      "Bar Charts",
      "Pie Charts",
      "Stem and Leaf",
      "Frequency Trees",
      "Two Way Tables",
      "Frequency Polygons",
      "Mean, Median, Mode and Range",
      "Averages from Frequency Tables",
      "Scatter Graphs",
      "Cumulative Frequency",
      "Box Plots",
      "Histograms",
    ],
  },
  {
    id: 6,
    name: "Probability",
    topics: [
      "Probability",
      "Relative Frequency (within Probability)",
      "Probability Trees",
      "Venn Diagrams",
      "Conditional Probability",
      "Probability Equation Questions",
    ],
  },
]
